version: '3.8'

services:
  app:
    build:
      context: .
    image: cinco-chat
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-time-zone='+00:00'
    networks:
      - my_network
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      
networks:
  my_network:
    driver: bridge